### ISSUE TITLE
<path_to_bro_build> issue

### ISSUE THREAD

**Issue by binups** [bro/bro-plugins#27]
Hi,
                I am using  security onion OS and  bro is already installed in this OS , i dont know the "path_to_bro_build"  please suggest

**Comment by 0xxon** [comment]
If you want to build one of the plugins that is not included by security onion, you will have to provide a Bro source directory, which was used to build the installed Bro version. This might entail rebuilding Bro, if it is not provided by security onion.

Since this is not actually a bug, please ask further details either on the security onion or on the Bro mailing lists.
