### ISSUE TITLE
Add field replacement for kafka output

### ISSUE THREAD

**Issue by spartan782** [bro/bro-plugins#35]
It would be really helpful to have the ability to replace some of the bro fields that contain dots with underscores with some kind of option or variable set. Kafka hands these fine obviously but other things once it leaves kakfa don't. Also perhaps there is already a way but is it possible to push all logs to kakfa?

**Comment by 0xxon** [comment]
Hi,

Changing the . in field names was added in (and around) https://github.com/bro/bro/commit/b28801ce9508250594a8e3c6483f3176483d790c - look at testing/btest/scripts/base/frameworks/logging/unrolling_sep_and_field_name_map.bro for an example.

You should be able to easily adapt the https://github.com/bro/bro-plugins/blob/master/kafka/scripts/Bro/Kafka/logs-to-kafka.bro script to send all logs to kafka - simply remove the if condition checking the log name.

Generally, these kind of questions are more suited for our community mailing list at http://mailman.icsi.berkeley.edu/mailman/listinfo/bro since they are not really bugs. I hope this helped :)
